CREATE TABLE employee (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR(30) NOT NULL,
    last_name VARCHAR(30) NOT NULL,
    role VARCHAR(30) NOT NULL,
    department VARCHAR(30) NOT NULL 
    );

CREATE TABLE department (
id INT NOT NULL AUTO_INCREMENT,
department VARCHAR(30) NOT NULL 
PRIMARY KEY (id)
);